server:
  port: 8761

spring:
  application:
    name: service-registry

#disable as client
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
